/*
 * HWmapping_iTrackingV1.2.h
 *
 *  Created on: Apr 7, 2017
 *      Author: dv198
 */

#ifndef EXTRA_HWMAPPING_ITRACKINGV1_2_H_
#define EXTRA_HWMAPPING_ITRACKINGV1_2_H_

/* START */
#define APP_FLASHPAGE_ORIGIN	52
#define APP_FLASHPAGE_NUM		(179 - 52 + 1)

#define BKPDR_BOOTSEL			BKP_DR1
#define BKPDR_UPGFW_MAINVER		BKP_DR2
#define BKPDR_UPGFW_SUBVER		BKP_DR3
#define BKPDR_RESETEVENTS		BKP_DR4
#define BKPDR_EG_ADC			BKP_DR5

#define TERM_UARTPORT		1
#define GNSS_UARTPORT		3
#define GNSS_UART_BRATE		9600
#define GNSS_UART_BRATE2	4800
#define GSM_UARTPORT		2
#define CAM_UARTPORT		5

#define GNSS_PWRCTRL_PORT		IOPORT_B
#define GNSS_PWRCTRL_PIN		15
#define GNSS_RST_PORT			IOPORT_B
#define GNSS_RST_PIN			1
#define GSM_PWRDWN_PORT			IOPORT_B
#define GSM_PWRDWN_PIN			7
#define GSM_RST_PORT			IOPORT_B
#define GSM_RST_PIN				0
#define EXTRS232_PWRCTRL_PORT 	IOPORT_A
#define EXTRS232_PWRCTRL_PIN 	15
#define SDC_PWR_PIN				GPIO_Pin_14
#define SDC_PWR_PORT			GPIOB
#define SDC_CS_PIN				GPIO_Pin_4
#define SDC_CS_PORT				GPIOA
#define LEDPWR_PORT				IOPORT_B
#define LEDPWR_PIN				5
#define KEYSIGNAL_PORT			IOPORT_C
#define KEYSIGNAL_PIN			4
#define DOORSIGNAL_PORT			IOPORT_C
#define DOORSIGNAL_PIN			0
#define ANALOG_SIGNAL_PORT		IOPORT_C
#define ANALOG_SIGNAL_PIN		3
#define WHEELPULSE_SIGNAL_PORT	IOPORT_C
#define WHEELPULSE_SIGNAL_PIN	2
#define ACSIGNAL_PORT			IOPORT_C
#define ACSIGNAL_PIN			6
#define BUZZER_PORT				IOPORT_B
#define BUZZER_PIN				12

#define ANALOGIN_ADCx		1
#define ANALOGIN_ADC_CH		13
#endif /* EXTRA_HWMAPPING_ITRACKINGV1_2_H_ */
